<?php

namespace AppBundle\Repository;

/**
 * Quiz_QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Quiz_QuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
