<?php

namespace AppBundle\Repository;

/**
 * UserTopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTopRepository extends \Doctrine\ORM\EntityRepository
{
//    /**
//     *
//     */
//    public function getMaxPoints()
//    {
//        $em = $this->getDoctrine()->getManager();
//        $query = $em->createQuery(
//            'SELECT `points` FROM `app_user_top` ORDER BY `points` DESC LIMIT 3'
//        );
//        $products = $query->getResult();
//    }
}
