<?php

namespace AppBundle\Repository;

/**
 * UserTopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTopRepository extends \Doctrine\ORM\EntityRepository
{
}
