<?php

namespace AppBundle\Repository;

/**
 * userAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
