# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
                ROLE_ADMIN:    ROLE_USER
                ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            form_login:
                default_target_path: mainMenu
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /login
    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/user, roles: ROLE_USER }